### ISSUE TITLE
Dicom Compression Not Working

### ISSUE THREAD

**Issue by ky-tech-guy** [bettar/miele-lxiv#10]
When I try to compress a dicom dataset from uncompressed to JPEG 2000, nothing happens.  This Feature works in Osirix 5.8.2.  If you need an uncompressed dataset for testing let me know.  
![screen shot 2015-04-08 at 10 29 51 pm](https://cloud.githubusercontent.com/assets/10901615/7059424/f342a076-de3e-11e4-829d-6bc6451ea832.jpg)

**Comment by bettar** [comment]
It's been fixed in release "b13".
