### ISSUE TITLE
dysfunction of multi-window image split

### ISSUE THREAD

**Issue by yeralp** [bettar/miele-lxiv#101]
Hi, The double horizontal split window pane does not work. When you select that option, images are split into four windows. Is it possible to work this out? Thanks

**Comment by bettar** [comment]
Can you please be more specific about the steps to reproduce the issue ?
Also, possibly attach a screenshot.
Also, please mention the version of macOS, version of the app, and CPU architecture.

**Comment by yeralp** [comment]
Hi,

In my previous mail I have provided the requested information, but have not received any responses since then. Any suggestions regarding my issue??

thanks

Yesim

**Comment by bettar** [comment]
in your previous mail to whom ? I certainly haven't received emails directly from you. Please post the "requested information" here.
