### ISSUE TITLE
miele lxiv not working

### ISSUE THREAD

**Issue by paget1985** [bettar/miele-lxiv#103]
I purchased miele lxiv and use it for 2 months after that it stops working, can't open the program on my imac or mac air

**Comment by paget1985** [comment]
I unstalled the program and installed it again but still I can't open it

**Comment by bettar** [comment]
Can you please provide more more information on you macOS versions, and the app version ? Are you saying that the same app version worked for 2 months on two computers, then all of a sudden the same version stopped working on both machines ? Can you give me some clues as to why it stopped working ?

**Comment by zdavatz** [comment]
How did you uninstall and reinstall @paget1985 ?

**Comment by zdavatz** [comment]
Did you use the free version before he bought the version @paget1985 ?

**Comment by paget1985** [comment]
I have the full version purchased through app store since the beginning, i think the problem started when i did the update, not sure 
my mac version 10.13.6
the app version 9.34

**Comment by paget1985** [comment]
> Can you please provide more more information on you macOS versions, and the app version ? Are you saying that the same app version worked for 2 months on two computers, then all of a sudden the same version stopped working on both machines ? Can you give me some clues as to why it stopped working ?

I have the full version purchased through app store since the beginning, i think the problem started when i did the update, not sure
my mac version 10.13.6
the app version 9.34

**Comment by paget1985** [comment]
> Did you use the free version before he bought the version @paget1985 ?

I have the full version purchased through app store since the beginning, i think the problem started when i did the update, not sure
my mac version 10.13.6
the app version 9.34

**Comment by paget1985** [comment]
> How did you uninstall and reinstall @paget1985 ?

i deleted it form the application and downloaded again through app store

**Comment by bettar** [comment]
Please refer to issue #92

**Comment by zdavatz** [comment]
> > Did you use the free version before he bought the version @paget1985 ?
> 
> I have the full version purchased through app store since the beginning, i think the problem started when i did the update, not sure my mac version 10.13.6 the app version 9.34

Can you do more Updates on that Mac? What is the exact model of the Mac? Laptop, iMac, etc which year did you buy it?

**Comment by paget1985** [comment]
ّ I download it on my Imac 10.13.6 bought it 2010
and MAC AIR 10.14.6 bought around 2016

on bith it is not working, when I click the app logo it fades out and disappear and an apple massage appears stating: IGNORE, REOPEN, and SEND REPROT
________________________________
من: Zeno R.R. Davatz ***@***.***>
‏‏تم الإرسال: 20/ربيع الثاني/1445 09:49 م
إلى: bettar/miele-lxiv ***@***.***>
نسخة: paget1985 ***@***.***>; Mention ***@***.***>
‏‏الموضوع: Re: [bettar/miele-lxiv] miele lxiv not working (Issue #103)


Did you use the free version before he bought the version @paget1985<https://github.com/paget1985> ?

I have the full version purchased through app store since the beginning, i think the problem started when i did the update, not sure my mac version 10.13.6 the app version 9.34

Can you do more Updates on that Mac? What is the exact model of the Mac? Laptop, iMac, etc which year did you buy it?

**Comment by zdavatz** [comment]
> ّ I download it on my Imac 10.13.6 bought it 2010 and MAC AIR 10.14.6 bought around 2016 on bith it is not working, when I click the app logo it fades out and disappear and an apple massage appears stating: IGNORE, REOPEN, and SEND REPROT

What kind of Mac is it? Can you please share the serial number of both Macs?

Settings > About this Mac
