### ISSUE TITLE
Miele-LXIV crashes on launch

### ISSUE THREAD

**Issue by MacValej** [bettar/miele-lxiv#105]
Just purchased this 10-30-23 from App store using MoJave 10.14.6  will not start at all.

**Comment by bettar** [comment]
Please refer to issue #92

**Comment by drtaverasl** [comment]
I have the same issue...
I have a MacBook Pro (13-inch, Mid 2012), with macOS Catalina, version 10.15.7.
What can I do?

**Comment by bettar** [comment]
> What can I do?

I would suggest any of these solutions:

1. wait for the next release of the app to see if the problem goes away
2. ask for a refund from Apple
3. try to get hold of an earlier version of the app (before 9.34.128)
4. update your hardware with a machine and macOS version that is currently supported by Apple

**Comment by bettar** [comment]
See #92
