### ISSUE TITLE
Pre-built Binary version 6.2.b11 cannot run on OS X 10.10.2

### ISSUE THREAD

**Issue by kbloh** [bettar/miele-lxiv#11]
The pre-built binary of Osiri-LXIV version 6.2.b11 which was released on 8 April 2015 cannot run on OS X 10.10.2.
Error msg showed the app no compatible with the OS version.

**Comment by bettar** [comment]
Please read the Note for version b10 on this page http://bettar.no-ip.org/lxiv/changelog.html
