### ISSUE TITLE
This version of has not been validated or certified for this version of MacOS

### ISSUE THREAD

**Issue by needz** [bettar/miele-lxiv#114]
I am running the latest Apps Store version of Miele-LXIV on macOS Sonoma 14.3 and I receive the following notice:

"This version of Miele-LXIV has not been validated or certified for this version of MacOS. Bugs, errors and instabilities can occur. Upgrade to latest version of Miele-LXIV to solve this problem."

Is this a general issue? Or should I try something on my side?

<img width="114" alt="Screenshot 2024-01-26 at 10 58 20" src="https://github.com/bettar/miele-lxiv/assets/1172243/e14959dc-db1a-4e4b-be42-85ec00d16c72">
<img width="246" alt="Screenshot 2024-01-26 at 10 58 06" src="https://github.com/bettar/miele-lxiv/assets/1172243/449bf82b-dba5-473f-b094-b6bea8c90f8a">

**Comment by bettar** [comment]
it's just a warning, the validated new version will be available in the next few days

**Comment by bettar** [comment]
This warning will be turned off in future releases.
