### ISSUE TITLE
[BUG] PET/CT fusion images have unfixable windowing/opacity (Version 9.39)

### ISSUE THREAD

**Issue by ihrapsa** [bettar/miele-lxiv#116]
## **Issue Description:**

There seems to be an issue with the windowing of the CT from the fused PET/CT image. Changing the window/contrast or opacity function doesn't fix this. There's nothing wrong with the CT when opened alone with the 2D Viewer. The CT windowing also gets fixed if the PET fusion is hidden (CMD+Shift+F). Here is a screenshot for reference.

![Screenshot 2024-04-03 at 16 02 14](https://github.com/bettar/miele-lxiv/assets/40600040/4b5d6ff5-fb6b-4119-acb4-3185edc336a8)

Also, sometimes everything turns into a beautiful sunset gradient. 
![Screenshot 2024-04-03 at 16 26 18](https://github.com/bettar/miele-lxiv/assets/40600040/a6f072e2-4a76-4d13-b756-1349827304fc)

## **Issue Reproduction:**

**1.** Load the PT and CT series together with 2D Viewer.
The fused PET/CT window will have a fixed window twitch very low contrast for soft tissue.  Changing the contrast or window does nothing.

**2.** Sometimes after closing the current view and reopening it I’m seeing that gradient. After restarting the app, the 2D viewer returns to the main CT unfixable windowing issue.

**Comment by bettar** [comment]
Fixed in version 9.40 to be released beginning of May 2024
