### ISSUE TITLE
possible bug: extra white space in AETitle field?

### ISSUE THREAD

**Issue by azankl** [bettar/miele-lxiv#118]
When I try to query my hospital's PACS with Miele, nothing happens (no error message, but also no images retrieved). When I do the same with Osirix, it works as expected. When trying to find the reason, I noticed that the 'Retrieve to' field looks slightly different between Osirix and Miele:

Osirix:
<img width="463" alt="Osirix" src="https://github.com/bettar/miele-lxiv/assets/4812335/d7f87377-b99b-4be8-b10f-3dac2041984d">

Miele:
<img width="348" alt="Miele" src="https://github.com/bettar/miele-lxiv/assets/4812335/3fd157c0-691e-4043-b817-1b4acc29e529">

It looks like in Miele, there is some extra white space or a tab after the AETitle (Horos). Could this be causing the problem? I remember my hospital IT team telling me that the AETitle has to be Horos, so any added white space or tab characters might cause the connection to fail.

Thanks
Andreas

**Comment by bettar** [comment]
Are you having troubles removing that extra white space ?

**Comment by azankl** [comment]
Managed to fix the problem, had nothing to do with the whitespace issue. This can be closed.
