### ISSUE TITLE
DICOM compression JPEG LS issue

### ISSUE THREAD

**Issue by ky-tech-guy** [bettar/miele-lxiv#12]
When I compress dicom images with the JPEG LS compression scheme, the images become blank.  I tried changing the windowing and this did fix the problem.   See the image below for details.
![screen shot 2015-04-09 at 12 43 36 pm](https://cloud.githubusercontent.com/assets/10901615/7071952/92db87de-deb6-11e4-898d-8a1ecfa7725b.jpg)

**Comment by bettar** [comment]
The JPEG LS compression/decompression is actually working. It's just the displaying of JPEG LS compressed data that is broken.
It's been fixed in version b14
