### ISSUE TITLE
The app Miele LXIV quit unexpectedly immediately after launching

### ISSUE THREAD

**Issue by FerasFahim** [bettar/miele-lxiv#120]
Even after deleting it and reinstall it does the same

**Comment by FerasFahim** [comment]
I contact Apple support team and they run some troubleshooting steps and they advised that I should contact the developer

**Comment by bettar** [comment]
1. First thing to do would be knowing your OS version, hardware details and CPU architecture.
2. Then it would help to know if you get any error messages (try launching the app from Terminal)
3. Do you have any DICOM files in the database ?
4. Try deleting the database directory (make a backup first)
5. Try launching the app in protected mode.
6. Did the app ever run without crashing ?
