### ISSUE TITLE
2D Viewer Thumbnails List not showing

### ISSUE THREAD

**Issue by jimbito1** [bettar/miele-lxiv#122]
Hi there! I use miele and its great! Im having a problem now, the window tiling is like blocked, I can't use it any more. I use it with columns so I can compare images. If you can help me would be amazing. Thanks! Marcos

**Comment by bettar** [comment]
What do you mean by "window tiling", can you attach some screenshots ? Also, what do you mean by "blocked" ? What macOS version are you using ? What CPU architecture ?

**Comment by jimbito1** [comment]
Dear Alex, thanks for you answer!
This is the screenshot. My wife needs to informe medical images and she need to compare the images in colums. Thats why she use this option. I mean ``blocked`` since she cant use it any more. The numbers used to be in white when it was available but now its grey.

Here is the mac info. Sorry im not really good with technology.

Best regards,
<https://1drv.ms/i/s!ArBaNiaqdlfFhEAb0jQmMFkD7QX3>
[https://wdzbpw.ph.files.1drv.com/y4mh_dUgsGxPNsNzcvJeb9xs54Bqd8PjXxSd0pOh-kzmSWgryW4Ng84X8Bcn87iLVg1ubRBRwf_5MTLejq0rarcE14Go_0jgyrPjrbTw7U7tuN28eE96oWOD65uyDmfVfippJlU3vi8dGDmJ9l9IOhZMV4pfZTMMo_SndXNiueqt5DOrI29MJCD2JUjVxJmIKmanpcy-jvxO1TlZHFSdtWvyw?width=200&height=150&cropmode=center]
[https://res.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]Captura de Pantalla 2024-08-14 a la(s) 09.46.55.png

Marcos Martinicchio
________________________________
De: Alex Bettarini ***@***.***>
Enviado: miércoles, 14 de agosto de 2024 9:31
Para: bettar/miele-lxiv ***@***.***>
Cc: jimbito1 ***@***.***>; Author ***@***.***>
Asunto: Re: [bettar/miele-lxiv] consult (Issue #122)


What do you mean by "window tiling", can you attach some screenshots ? Also, what do you mean by "blocked" ? What macOS version are you using ? What CPU architecture ?

**Comment by Rud34** [comment]
Dear Alex Bettarini, 
Hi,
The day before yesterday I sent you a letter through the support within the program, apparently it did not arrive.
The problem is as follows: after the last update of the program, the display of the series list column of the open study disappeared (I am attaching a screenshot). Before the update, everything worked fine and the column on the left was present. I thought that something went wrong, deleted the program and reinstalled it from the Appstore. But the problem was not solved.
At the same time, the checkbox in 2D Viewer is checked, the key combination also does not include the series list.
I hope this problem will be solved.
Best regards.

<img width="523" alt="image" src="https://github.com/user-attachments/assets/35e6ed4c-528b-46e3-b089-c41d9cb54ffa">

**Comment by bettar** [comment]
Just deleting the app is not the cleanest way of uninstalling it, because the database directory and the preferences file are still left untouched.

**Comment by Rud34** [comment]
> Just deleting the app is not the cleanest way of uninstalling it, because the database directory and the preferences file are still left untouched.

What should I do to fix this?

**Comment by bettar** [comment]
I can now reproduce on my system the issue of the "Thumbnails View" not showing on the left of the screen. Please wait for the next release of the app.

**Comment by jimbito1** [comment]
![thumbnail_Imagen 14-8-24 a las 09 35](https://github.com/user-attachments/assets/f08c1c7c-e423-49b6-9ee5-781ab2b243af)

**Comment by jimbito1** [comment]
Hi Alex, is this problem related to an update of the program? do you think it will be fixed? my wife really use it! Its the bes one! Thanks!
![thumbnail_Imagen 14-8-24 a las 09 35-2](https://github.com/user-attachments/assets/acf0a0f7-d664-4a0c-a9f2-0f1014313270)

**Comment by bettar** [comment]
Please create a new issue if it's unrelated. You cannot select the Windows Tiling because the popup is grey and unclickable ? Is that it ? Did it use to work in the previous version of the app ?

**Comment by bettar** [comment]
The issue of the "Thumbnails View" not showing on the left of the screen has been fixed. Please wait for the next release of the app, version 9.42.148
If you want to get it working on the current version 9.41.146, use the workaround below:

**Comment by bettar** [comment]
Type the following in Terminal

defaults write ~/Library/Preferences/com.bettarini.miele-lxiv.plist UseFloatingThumbnailsList -bool false
