### ISSUE TITLE
how to import existing Osirix databases?

### ISSUE THREAD

**Issue by azankl** [bettar/miele-lxiv#123]
I have 2 large (100GB) Osirix databases (created with Osirix MD 14.0) that I want to import in to Miele-LXIV. What is the best way to do that? I tried simply opening the Osirix Data folder with Miele-LXIV, that did not work. Renaming the 'Osirix Data' folder to 'Miele-LXIV Data' also did not work. I tried creating a new Miele-LXIV Database with the 'New Database' command and then dragging the Osirix Data folder into Miele-LXIV. That works and seems to import all images from the Osirix database, but its very slow. Is there a better way to do this?

**Comment by bettar** [comment]
The program you are importing from (they already sued me in court for mentioning their name) is no longer open source, and most likely their data base structure has diverged, so the approach of simply re-importing the DICOM files (and only those ones) is what I would recommend. You say it is "slow"... can you quantify "slow" ? is it in the order of 1 hour, 1 day or 1 week ? 100GB of files is a lot of data but the important thing it that you say "that works". Why do you worry about finding a better way, are you planning to do it again ?

**Comment by azankl** [comment]
Thanks. I only imported a small test database from Osirix to Miele-LXIV and that worked. I just wanted to double check with you that this is the best way before attempting the larger databases.

**Comment by xenophon61** [comment]
Renaming "Horos Data" worked for me. After a brief message of "recalculating UUIDs", everything was in order. To me, this seems to be a valid method of migrating (from Horos, not Osirix which I have long abandoned).

Take care, and thanks for a great project!

Xen
