### ISSUE TITLE
 Windows Tiling 

### ISSUE THREAD

**Issue by jimbito1** [bettar/miele-lxiv#124]
Hi!
because the popup is grey and unclickable ? 
Yes
Is that it ? Did it use to work in the previous version of the app ? 
Yes it worked perfectly.

![thumbnail_Imagen 14-8-24 a las 09 35-2](https://github.com/user-attachments/assets/3f4335af-881c-4beb-b790-04c8b2b9f811)

**Comment by bettar** [comment]
How about customising the toolbar by adding the Windows Tiling button?

**Comment by jimbito1** [comment]
Hi Alex, yes I do have the button, but this is what happen when I use it from there...
<img width="1440" alt="Captura de Pantalla 2024-08-19 a la(s) 08 32 07" src="https://github.com/user-attachments/assets/bfb9fcc4-b392-4b46-ab22-88672a409183">

I click 2 columns, but opens 4 squares.
<img width="1440" alt="Captura de Pantalla 2024-08-19 a la(s) 08 31 45" src="https://github.com/user-attachments/assets/e36f4800-c68f-4544-a6f8-f176bef6b9e1">

**Comment by bettar** [comment]
Yes, I could confirm that this Windows Tiling functionality is broken. I'll try to fix it for the next release.

**Comment by jimbito1** [comment]
Alex, thanks for your answer and your time! Regards.
