### ISSUE TITLE
DICOM editing in OS dark mode: edited value not visible when field is active

### ISSUE THREAD

**Issue by jujar** [bettar/miele-lxiv#128]
When editing a DICOM field's value and MacOS dark mode is active, when I activate the field to be edited, I cannot see the field's value unless I highlight the text. I. E. the field being edited has a white background with white text. Can this be improved in future versions?
<img width="962" alt="dicom_edit" src="https://github.com/user-attachments/assets/6ce1493a-c67e-4aa8-b8f1-ecdf2afb1bfc">

**Comment by bettar** [comment]
Fixed! Please wait for the next release, version 9.44

**Comment by jujar** [comment]
Excellent, thank you so much!
