### ISSUE TITLE
Upgrade button displays on application startup

### ISSUE THREAD

**Issue by ky-tech-guy** [bettar/miele-lxiv#13]
There is an annoying button/banner that displays on the bottom of the screen that prompts you to upgrade to the Pixmeo Osirix 64-bit.  It only appears transiently and then disappears.  See the image below for details.  
![screen shot 2015-04-09 at 12 50 26 pm](https://cloud.githubusercontent.com/assets/10901615/7072085/b3973a12-deb7-11e4-9437-fc5b8da8b7a5.jpg)

**Comment by bettar** [comment]
Okay. I have greyed out the image in release b13. I will prevent the flashing in a future release.
