### ISSUE TITLE
Web Server Not working

### ISSUE THREAD

**Issue by kas4u2** [bettar/miele-lxiv#134]
Hello, I want to use the web server but when I am activating it, It doesn't connect. Basically its not working.
I am on the same network.

Although, On Horos app, its working. 

Please if there is any solution or an update of the app, please let me know.
Thank you.

**Comment by bettar** [comment]
Are you sure the two servers are not running at the same time, trying to use the same port ?

**Comment by kas4u2** [comment]
> Are you sure the two servers are not running at the same time, trying to use the same port ?

I tried by disabling the horos web server, by uninstalling fully horos app... 

Also tried with the same port and different port too.

**Comment by bettar** [comment]
It's been fixed for next version 9.45, to be release middle of Dec 2024

**Comment by kas4u2** [comment]
> It's been fixed for next version 9.45, to be release middle of Dec 2024

Ok. Thank you.
Will update whenever is available and I will let you know if the problem is solved for me or not ! 
Thank you again for a quick response 🙏

**Comment by bettar** [comment]
Can you confirm that the issue has been fixed in the latest release ?

**Comment by kas4u2** [comment]
> Can you confirm that the issue has been fixed in the latest release ?

Thanks a bunch ! Its working. ))
