### ISSUE TITLE
Cannot retreive image from PACS with latest version

### ISSUE THREAD

**Issue by manzing** [bettar/miele-lxiv#14]
Hi
Using the latest version 6.2 b12 (it could be the same with other recent versions, i may have missed some updates during last month) i cannot retrieve images from PACS anymore.
All parameters are the same as before, and retrieve works fine if i revert to an older version (6.0 b6 or 5.9).
The issue occured on Yosemite, as well as on OS 10.8.5.
The PACS is CONQUEST Dicom Server.
Thanks

**Comment by bettar** [comment]
Since version b7 the project is using DCMTK version 3.6.1
Check with the Console.app for some error messages. If you are up to it, you can use Wireshark to check at which stage the retrieve fails. If you give me access to the PACS I can check it for you.

**Comment by bettar** [comment]
Are you still having the same problem with the latest version 6.2.15 ?

**Comment by manzing** [comment]
I've just tried the 6.2.16 version this morning and the retrieve function works perfectly now.
Thank you for the fix.
