### ISSUE TITLE
Multiple languages support

### ISSUE THREAD

**Issue by atemper** [bettar/miele-lxiv#15]
Only English and Japanese languages are presented. How do I add more languages as the Osirix Lite?

**Comment by bettar** [comment]
The localised resource files have never been open source. You could try copy/paste the "flattened" files (the whole <language>.lproj directory) into Contents/Resources/ for the language you are interested in from another version of OsiriX, but there are going to be some differences. To correct minor differences you could regenerate and replace only the affected NIBs by using the application iLocalize. If you have some other suggestion or a specific request let me know.

**Comment by bettar** [comment]
As of Dec 2018 the new release, version 7.1.30 supports 7 languages
