### ISSUE TITLE
Support for C-MOVE SCP?

### ISSUE THREAD

**Issue by Jo-Vo** [bettar/miele-lxiv#16]
Seems I cannot retrieve images from a Sectra PACS Server (works with about every OsiriX version at least from 6.x).
This PACS seems to use C-MOVE SCP, which is selectable in the preferences with OsiriX(Lite) but not Osiri-LXIV

**Comment by bettar** [comment]
Could you possibly give me access to that server so I can check out what the problem is ?

**Comment by Jo-Vo** [comment]
That's a bit difficult because the server only accepts known nodes. Every send destination has to be configured there with IP, AETitle, and port.

Falter $.91 note

**Comment by Jo-Vo** [comment]
Stupid speech recognition..
Fortunately one of the set up send destinations has a DNS, so I could temporary route this to your IP - you wouldn't have to use the preset AETitle and port and then it should..

Should I contact you via email for this?

**Comment by Jo-Vo** [comment]
The above should of course read "you would have to"...

**Comment by bettar** [comment]
Yes, contact me via email.

**Comment by Jo-Vo** [comment]
OK, now it works with the new b15; the issue can be marked as solved/closed.

Thanks for the fast and personal support.
