### ISSUE TITLE
Osiri-LXIV 6.2.b14 c-echo failed

### ISSUE THREAD

**Issue by atemper** [bettar/miele-lxiv#17]
Cannot dicom ping to this version.  The 'Activate C-GET SCP' and 'Activate C-FIND' were checked.

**Comment by bettar** [comment]
Can you please send me an email with your server parameters so I can replicate the problem and try to fix it ?

**Comment by atemper** [comment]
I installed Osiri-LVIV and OsiriX Lite on two MAC machines (one is MAC MINI, another one is MAC Book AIR). In the same network I installed  ClearCanvas on another  Windows machine. I can verify Osirix Lite but not the LVIV 6.2 from clearcanvas. Both Osirix instances are newly installed. I switched the two  Osirix instances between two machines got the same result.

**Comment by bettar** [comment]
In the Preferences, Listener, is the "Activate DICOM listener..." ticked ? Did you restart the program after making any changes to those settings ?

**Comment by bettar** [comment]
Are you still having the same problem ?

**Comment by atemper** [comment]
Cool,6.2.15 works.
