### ISSUE TITLE
Unable to create DICOM PDF

### ISSUE THREAD

**Issue by defeco** [bettar/miele-lxiv#18]
With the latest 2 versions of Osiri-LXIV on Yosemite, I am not able to create a DICOM PDF when there is a MS Word report for the selected study using File > Report > Convert to DICOM PDF. If I remember correctly, this feature functioned correctly on the earlier versions of Osiri-LXIV. With Osirix 5.8.2 and Osirix Lite 6.5.1, this feature is functioning.

**Comment by bettar** [comment]
Fixed in release 6.2.16
