### ISSUE TITLE
can no longer see databases and sources drawer

### ISSUE THREAD

**Issue by azankl** [bettar/miele-lxiv#2]
databases and sources drawer not showing for me since installing v6.0b5. Choosing 'Toggle databases and sources drawer' in File menu also does not work.

**Comment by bettar** [comment]
On 10/03/15 14:03, Andreas Zankl wrote:

> databases and sources drawer not showing for me since installing
> v6.0b5. Choosing 'Toggle databases and sources drawer' in File menu
> also does not work.
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/bettar/osirix/issues/2

Hi Andreas,

try dragging the margin with the mouse to make them visible. You should
need to do this only the first time. It should be okay on Yosemite. I am
still looking into a similar issue in Mountain Lion. What OS X version
are you running ?

Let me know if my advice solved the problem.

Cheers,
Alex Bettarini

**Comment by azankl** [comment]
Hi Alex,

I am on Yosemite (10.10.2), but dragging out the margin as you suggested
has fixed it and I only had to do it once.
Thanks!
Andreas
