### ISSUE TITLE
Problem when xcodebuild -target "OsiriX"

### ISSUE THREAD

**Issue by andrefiorot** [bettar/miele-lxiv#20]
I have problem when compiling
osirix-lxiv/DCM Framework/jpegdatasrc.m:22:10: fatal error: 'jinclude12.h' file not found
# include "jinclude12.h"

```
     ^
```

1 error generated.

*\* BUILD FAILED **

**Comment by bettar** [comment]
Did you read the file `doc/readme-compilation.md` ?
