### ISSUE TITLE
No image preview in main database

### ISSUE THREAD

**Issue by honestjohn101** [bettar/miele-lxiv#23]
Has anyone got any advice?

I have installed the latest version of Osiri-LXIV on an iMac with the latest Mac OS updates. It works brilliantly, but there is no preview window to display the DICOMs in the main database view. Similarly I can only see the dicom series listed by name, but with no preview thumbnails.

I think this was listed as a bug previously, but I believe it has been fixed.

Any suggestions anyone? It must be a specific issue with my Mac, as I installed it on another machine and the preview window was displayed fine. I've tried reinstalling the software a couple of times to no avail.

My apologies if this has already been answered previously.  I looked but couldn't see it.

Thanks.

**Comment by Jo-Vo** [comment]
Do you have a screenshot? Maybe the Preview-Area of the database window is just minimized?
If the Database list fits the whole window try going to the lower blue border and then pull up while holding the left mouse button..

**Comment by honestjohn101** [comment]
Many thanks for your suggestion - I really appreciate it. I'm currently not able to get a screenshot, but I'll test it out in a few days and get back to you. thank you again.

**Comment by honestjohn101** [comment]
Thank you again. To my delight this remedied the problem - how embarrassing - I just hadn't realised you could do that... Thanks again for your help.

**Comment by Jo-Vo** [comment]
I thought it was this "problem", because I nearly stumbled over this as well some time ago... ;)
