### ISSUE TITLE
database incompatibility with new osirix vesions

### ISSUE THREAD

**Issue by efnikos2000** [bettar/miele-lxiv#26]
Hi, it seems to be an incompatibility of databases with new osirix versions.
Is there any way to overcome this problem and have both applications ?

thank you

**Comment by bettar** [comment]
On 28/02/17 15:43, efnikos2000 wrote:
> Hi, it seems to be an incompatibility of databases with new osirix versions.
> Is there any way to overcome this problem and have both applications ?
> 
> 
> thank you
> 
There could be legal issues in trying to maintain compatibility, besides
the technical issue. I have already been approached by Pixmeo's lawyers,
so for the moment I'm holding back on any promises.

**Comment by efnikos2000** [comment]
Ok, thank you.



2017-03-01 0:14 GMT+02:00 Alex Bettarini <notifications@github.com>:
