### ISSUE TITLE
Auto quit silently, without error message, after a few seconds

### ISSUE THREAD

**Issue by lepreincorsa** [bettar/miele-lxiv#27]
It seems working just for a few seconds.
Auto quit silently, without error message, after a few seconds.

any suggest?! please help.

**Comment by lepreincorsa** [comment]
Mac OS Sierra 10.12.6

**Comment by mlewis1973** [comment]
I was able to fix this by doing the following:
when you open Osiri-XLVI, quickly go to Preferences->General, uncheck the 2 boxes for auto-update, 
and then quickly close all windows, and restart Osiri-XLIV.

if you are fast enough and disable the checks for updates, this may stop the crash.
good luck
mlewis
