### ISSUE TITLE
Installed Plugins Auto-Update-Check may be an issue on high Sierra.

### ISSUE THREAD

**Issue by zdavatz** [bettar/miele-lxiv#28]
1. I installed Miele-LVIX and opened it. Not a problem.
2. Then I installed this plugin: http://www.amdentalsoft.net/download/Dental3DPlugin.osirixplugin.zip
3. Then I restarted Miele_LVIX. Then it started to crash right after the restart.
4. Then I disabled the two Auto-Check Updates as mentioned in #27 and then Miele-LVIX did not crash anymore.

**Comment by bettar** [comment]
Thanks for suggesting this workaround. The latest version (7.1.31) shouldn't have this problem, because it checks for Updates in a different repository.
