### ISSUE TITLE
Dicom Print seem not working

### ISSUE THREAD

**Issue by PatrickRABEL** [bettar/miele-lxiv#3]
I tried to print using dicom print but it seem not working

**Comment by bettar** [comment]
On 11/03/15 00:59, PatrickRABEL wrote:

> I tried to print using dicom print but it seem not working
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bettar/osirix/issues/3

Please provide more information: what versions are you using ? Does it
work with other software ? Which one ? Did it ever work ? Do you get any
error messages ? Have you looked for clues in the Console log ? What
steps are you following ? At which point does it fail ?

**Comment by PatrickRABEL** [comment]
Sorry for my poor information, my configuration is : MacBook Air Core i5 8Go Ram OSX 10.9.5.
I tried with OSIRI LXIV Version 5.9b3 and 6.0b6, without any succed, after 1 or 2 sec I receive the message "Print Failed, Couldn't print images", there is no log in the console logs, i tried also with the DVTK and no log also in the console log and the DVTK, the issue seem coming before the dicom association start . for your information, it work's with OSIRIX 32 version 5.7
