### ISSUE TITLE
Osirix Web Server Not Working

### ISSUE THREAD

**Issue by ky-tech-guy** [bettar/miele-lxiv#4]
When I tried to activate the built in web server and typed the url into my web browser the Web Portal did not appear, it was blank.  I went into preferences -> then web server -> I clicked activate built in web server -> I restarted Osirix LXIV -> I double check to make sure that files were present in ~/Library/Application Support/Osirix/WebServicesHtml/

**Comment by bettar** [comment]
I cannot reproduce the problem. Did you append the port number to the URL in your browser ?

**Comment by ky-tech-guy** [comment]
Yes.  I added the :3333.

**Comment by ky-tech-guy** [comment]
Was able to get web server working.
