### ISSUE TITLE
7.3.46 build with Miele-LXIV-easy @rpath/libpng16.16.dylib error

### ISSUE THREAD

**Issue by zdavatz** [bettar/miele-lxiv#42]
With the latest build done by [Miele-Easy](https://github.com/bettar/miele-lxiv-easy) I get the following error:

```
dyld: Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /Users/zdavatz/software/miele-lxiv/source/miele-20190508_1741/miele-7.3.46/build/Distribution/miele-lxiv.app/Contents/MacOS/miele-lxiv
  Reason: image not found
(lldb)
```

Great Readme BTW!! Thank you!

**Comment by bettar** [comment]
The README file clearly tells you to build the Development configuration, and you are getting the error with the Distribution configuration. I suggest you first build the Development configuration as instructed.  One great advantage of building the Development configuration is that the application is not sandboxed !

**Comment by zdavatz** [comment]
thank you!
