### ISSUE TITLE
Wrong visualization of Newtom Cone Beam Orthopantomograph

### ISSUE THREAD

**Issue by PieroEvolution** [bettar/miele-lxiv#48]
as you can see when I retrieve images from NewTom ConeBeam Orthopantomograph
they are displayed in green/purple and.
[newtom.zip](https://github.com/bettar/miele-lxiv/files/3766294/newtom.zip)
Thank you for support

**Comment by bettar** [comment]
The built-in DICOM validator gives several warnings and errors, three of which might be relevant to this problem:
~~~
Error - Unrecognized enumerated value <0x3> for value 1 of attribute <Samples per Pixel>
Error - Unrecognized enumerated value <YBR_FULL> for value 1 of attribute <Photometric Interpretation>
Error - Missing attribute Type 1 Required Element=<PresentationLUTShape> Module=<DXImage>
~~~

**Comment by PieroEvolution** [comment]
Thank you for your answer.
At the moment I solved asking to pacs develoer disabling the compression on server pacs.
Systems is much slower but it works.

**Comment by bettar** [comment]
Are you sure the DICOM tag (0028,0004) "YBR_FULL" is correct in the image file ? If I just edit it and change it to "RGB" the image is displayed like this (make sure Preferences, General, "For Color JPEG..." is unticked)
![Screenshot1](https://user-images.githubusercontent.com/9733270/67573684-37085400-f739-11e9-9e7c-35f38c643931.png)

 I am guessing that the image was originally of type YBR but in the compression step it's been converted to RGB, and the entity making the compression maintained the wrong tag.
