### ISSUE TITLE
Support for miele Worklist server

### ISSUE THREAD

**Issue by auarstadtt** [bettar/miele-lxiv#49]
Hi Alex,

I plan to buy and use you app for creating a worklist server in my clinics.

Do you have a support email address of example or help for this app after the sell ?
Kind regards.
Antoine Adam

**Comment by bettar** [comment]
There is no support channel whatsoever, except for occasional emails and messages like this one. The app is just a GUI wrapper over the DCMTK server, and actually I should update it to the latest version, hopefully in the next few days.

The purpose of the app being for sale is to save the trouble of rebuilding the app from sources, besides of course the convenience of having a graphical interface.
