### ISSUE TITLE
MPR visualization broken

### ISSUE THREAD

**Issue by carnico** [bettar/miele-lxiv#5]
Hi,

first of all thanks for the software.

My 3D MPR visualization is broken, tested on 2 different macs (see the image attached).

It is a known issue?

Best Regards

**Comment by rflcrz** [comment]
Hi @carnico ,

I am not able to see the mentioned attached file.

**Comment by carnico** [comment]
Sorry, there was a problem with upload. Now it should be ok.

![screenshot 2015-03-13 19 27 30](https://cloud.githubusercontent.com/assets/11464824/6655569/23e33872-cac0-11e4-815b-710e483b3acd.png)

**Comment by bettar** [comment]
It is a know (to me) issue. It's under investigation. I have noticed it to appear when one of the axis is rotated to a position near to 0 degrees. Maybe in the porting of the application from 32-bit to 64-bit there is somewhere in the code a division by a very small quantity (how small it is would be different in the 32-bit and 64-bit code) possibly causing that problem to appear. Of course any developer is welcome to jump in and provide a fix for it.

**Comment by bettar** [comment]
A workaround has been identified and will be included in the next release. It greatly mitigates the problem and it seems to fix it when the "Ray cast : Super Sampling" parameter in Preference, 3D is set to a high value. Other developers with more time on their hands are welcome to look into this and provide better insight.
