### ISSUE TITLE
Unable to export to Photos (denied by sandbox)

### ISSUE THREAD

**Issue by garrettreid** [bettar/miele-lxiv#56]
First, thanks for your great work!

Due to default OS security settings, miele-lxiv cannot export to Photos on macOS Catalina (and I believe, [since Mojave](https://developer.apple.com/documentation/macos_release_notes/macos_mojave_10_14_release_notes)). It is denied by system sandbox policy:
> Sandbox: miele-lxiv(10041) deny(1) appleevent-send com.apple.photos

In order to not be denied by the sandbox, you need to request permission for automation; that means the [NSAppleEventsUsageDescription key](https://developer.apple.com/documentation/bundleresources/information_property_list/nsappleeventsusagedescription) in your info.plist and a call to [AEDeterminePermissionToAutomateTarget](https://developer.apple.com/documentation/coreservices/3025784-aedeterminepermissiontoautomatet). To be allowed to prompt, you'll also need to adopt the [hardened runtime](https://developer.apple.com/documentation/security/hardened_runtime).

The alternate (and more typical) approach would be to use PhotoKit to [request changes to the photo library](https://developer.apple.com/documentation/photokit/phphotolibrary/requesting_changes_to_the_photo_library). Since this is macOS, you'd need the [NSPhotoLibraryUsageDescription key](https://developer.apple.com/documentation/bundleresources/information_property_list/nsphotolibraryusagedescription) (NSPhotoLibraryAddUsageDescription is iOS only).

**Comment by bettar** [comment]
Thank you. I will use your advice for the next release
