### ISSUE TITLE
Shortened text fields in Query/Retrieve and Database windows

### ISSUE THREAD

**Issue by fco-pires** [bettar/miele-lxiv#62]
Hello. First of all, congratulations on your work. I am a longtime Horos user and I am testing Miele-XLIV. But I have a problem in the Query / Retrieve window, in which all the text fields in the study list (such as patient name, study description, referring physician) appear shortened, with a maximum of 8 characters. When I retrieve any study, the database shows these fields shortened in the same way, and the exam is split into three or four entries, with incomplete series in each. When I open the meta-data window for any of these exams, all information appears correctly, full names, without any data being shortened or truncated. None of this happens when I query or retrieve these same studies in Horos, from the same DICOM nodes.
For information, I am using version 8.3.60, installed from the App Store, on a MacBook Pro (Retina, 13-inch, Early 2015), with macOS 10.15.7. And I literally didn't change any Miele settings, other than importing the DICOM nodes.

**Comment by bettar** [comment]
The problem has been fixed for the next release. Thank you for reporting it.
