### ISSUE TITLE
Tool bars misaligned in axial, 3D MPR and 3D VR

### ISSUE THREAD

**Issue by techmdmac** [bettar/miele-lxiv#66]
Dear Mr. Bettarini
First of all thank you for your interest in maintaining and improving your Miele LXIV App. We are many users who are disappointed to see how Horos has been abandoned, which barely corrects the multiple errors that it has shown for several months with Big Sur, so we appreciate its effort even more.
In order to further improve the Miele LXIV, here are some observations regarding the toolbars that appear misaligned compared to Horos. I give you screenshots for you to check. 
![Horos 3D MPR](https://user-images.githubusercontent.com/58887624/111884418-db8bd580-89c1-11eb-9811-cfcd9e35f1a1.png)
![Horos axial view](https://user-images.githubusercontent.com/58887624/111884421-dfb7f300-89c1-11eb-9710-115af45cfd2c.png)
![Horos curved MPR](https://user-images.githubusercontent.com/58887624/111884422-dfb7f300-89c1-11eb-9771-26d3d8692a98.png)
![Miele 3D MPR](https://user-images.githubusercontent.com/58887624/111884423-e0e92000-89c1-11eb-96f2-1dc19fd7bc0a.png)
![MIele axial view](https://user-images.githubusercontent.com/58887624/111884425-e181b680-89c1-11eb-8b05-08f696e9545f.png)
![Miele curved MPR](https://user-images.githubusercontent.com/58887624/111884426-e181b680-89c1-11eb-9d28-bc5dcf7a3a46.png)

**Comment by bettar** [comment]
Fixed for next release, expected early Apr 2023.
