### ISSUE TITLE
Scissor ROI on 3D VR Image

### ISSUE THREAD

**Issue by techmdmac** [bettar/miele-lxiv#67]
![Captura de pantalla 2021-03-20 a las 21 45](https://user-images.githubusercontent.com/58887624/111886603-3677f980-89cf-11eb-8d6a-2226e513fc37.jpg)
Trim roi with scissors totally outside the trimmed area.

**Comment by techmdmac** [comment]
This issue only seen with macOS Big Sur, not with macOS Catalina.

**Comment by techmdmac** [comment]
Is there any solution ? Very annoying…

**Comment by bettar** [comment]
I cannot reproduce the error. What are the steps you are doing to reproduce the error ?

**Comment by techmdmac** [comment]
Simply choose the scissors tool and try to crop a 3D volume freehand: the desired cropping area is totally displaced from the place where the freehand roi was drawn. It plays constantly on fully updated macOS Monterey. See video I sent you by email.

**Comment by bettar** [comment]
I am starting to suspect that the code is missing a simple adjustment for when it's running with a Retina display. I don't have a Retina display so I don't see the problem. Can you confirm that you are running with a Retina display ?

**Comment by techmdmac** [comment]
Yes. I confirm. Thank you!

**Comment by zdavatz** [comment]
1. With Retina I get this:
<img width="1069" alt="Bildschirmfoto 2022-08-22 um 16 33 42" src="https://user-images.githubusercontent.com/4953/185947364-662c04cd-4427-4129-add5-3fc771980848.png">
2. Works well on the external monitor.

**Comment by bettar** [comment]
I need access to a PC with Retina display to fix this.

**Comment by bettar** [comment]
Fixed for next release, expected early Apr 2023.

**Comment by techmdmac** [comment]
Good news, let's test it and give you feedback. Thank you !
