### ISSUE TITLE
text with formatting errors in preferences viewers

### ISSUE THREAD

**Issue by techmdmac** [bettar/miele-lxiv#68]
The text in preferences-viewers, at least in the Spanish translation, appears badly formatted at the end of the options.
<img width="833" alt="Preferences" src="https://user-images.githubusercontent.com/58887624/111918330-e78c9b80-8a84-11eb-8017-92b01660ae1e.png">

**Comment by bettar** [comment]
Fixed for next release, expected early Apr 2023.
