### ISSUE TITLE
Always crashes when opening a remote database

### ISSUE THREAD

**Issue by jonathancolledge** [bettar/miele-lxiv#7]
This issue is consistently reproducible.

**Comment by bettar** [comment]
Please tell me the contents of the file "DB_VERSION" in the database you are trying to open ? And what version of Osiri-LXIV are you using ? Is it also reproducible with the latest version ?

**Comment by jonathancolledge** [comment]
DB version is 2.6
It happens with both OsiriX LXIV 5.9b3 and 6.1b7

**Comment by bettar** [comment]
DB version 2.6 is the new model introduced by OsiriX 6.5 and support for it has only started with "Osiri LXIV 6.1b8" so probably there is still some bug to be fixed.
By the way, the version number "Osiri LXIV 6.1b7" doesn't exist.
I was able to replicate the problem and now I am looking into it.

**Comment by bettar** [comment]
Please download the new release "Osiri-LXIV 6.2.b9" and confirm that the problem has been fixed. Remember that the local and remote OsiriX must both use the same DB version, in this case 2.6
