### ISSUE TITLE
Cannot display MRI images

### ISSUE THREAD

**Issue by JungleGenius** [bettar/miele-lxiv#71]
![virus](https://user-images.githubusercontent.com/11284739/152264318-77b0fc77-6bbb-4156-8107-97f4e5d96bb0.png)

**Comment by bettar** [comment]
The virus warning has nothing to do with the App Store version: the file in the screenshot is a user file that that particular user added to the database

**Comment by JungleGenius** [comment]
Yes I jumped the gun.  I didn't know your App created the database files or the container image (e.g. what you are asserting is a user file) as part of the image import process.

The malware/virus was actually embedded in a Windows based Medical Imaging (MRI Images) viewer included on the DVD along with my MRI Images.  From SimonMed too.

The App Store App attempted to import everything on the DVD including the JAR files for the Windows reader App included on the DVD.

One of the imported JAR files had the malware signature.

The design flaw trusting and not validating the files being imported...  Bobby Tables and whatnot.

And your App still would not display the MRI images after "successfully" importing just the image files and not the entire DVD.

Maybe its a image format you don't support.  Although it was a Philips MRI and not exactly brand new.  Although the metadata was fine.   Just a bunch of question ??? marks where I would expect thumbnails.

**Comment by bettar** [comment]
If you could email me those MRI images I can check why they are not displayed correctly.

**Comment by JungleGenius** [comment]
What email do you want me to send the files to?  Also what files?  DICOM ,  DICOMDIR,  IM000001 etc ???  Do you need the whole ISO?  Its all PPI ...

**Comment by bettar** [comment]
The email address can be the one that you find running the application, Help, "Send an email...".

In the email please outline the steps to reproduce the issue, and attach to the email the files required to reproduce those steps.
