### ISSUE TITLE
Error when the database is to be saved on an external hard drive

### ISSUE THREAD

**Issue by nabrurheuk** [bettar/miele-lxiv#75]
When I try to select a storage location on an external hard drive instead of the default location, I get the following error message the next time I start the programme:

"You do not have the rights to save the file "DATABASE.noindex" in the folder "Miele-LXIV Data"."
<img width="299" alt="Bildschirmfoto 2022-02-18 um 12 39 21" src="https://user-images.githubusercontent.com/58640565/154703436-6d0e6948-df00-40a9-b7f8-035b5c5d250d.png">

The programme runs on an Intel iMac with MacOS Big Sur operating system version 11.6.3. The external hard drive is configured to ignore owners on this volume. Miele has full Volume Access. The (empty) folder "Miele-LXIV Data" was created by the program itself after I selected the user database location.

<img width="567" alt="Bildschirmfoto 2022-02-18 um 15 40 10" src="https://user-images.githubusercontent.com/58640565/154703630-8dd99d0a-de99-44d0-966e-3b8f7070a288.png">

<img width="282" alt="Bildschirmfoto 2022-02-18 um 15 40 59" src="https://user-images.githubusercontent.com/58640565/154703782-2cf71c72-7d61-40b8-9674-1c2427c1d67a.png">

<img width="678" alt="Bildschirmfoto 2022-02-18 um 16 35 50" src="https://user-images.githubusercontent.com/58640565/154713477-e0ccea3a-781d-4fb4-a9e3-eb9893b8e3bf.png">

Saving to the file path "default database location" works fine. Unfortunately, I do not have enough free space on the internal hard disk.

Can anyone help me solve this problem?

**Comment by bettar** [comment]
It's a "sandboxing" issue, very annoying as usual. Supposedly fixed with version 8.17.88 being released now.
