### ISSUE TITLE
open rtstruct file

### ISSUE THREAD

**Issue by negarbarooti** [bettar/miele-lxiv#76]
hello i have a rtstrust file and when i open it on the app it says "This series contains RTSTRUCT ROIs. Should I generate the corresponding ROIs on the images series? "
and after i clicked ok but it doesnt work and it cant open it

**Comment by bettar** [comment]
If you can send me that RTSTRUCT file (to the email address shown in the app Help menu) I will take a look at it to see what is going wrong.

**Comment by negarbarooti** [comment]
thank you i sent it

**Comment by bettar** [comment]
Sorry but I haven't received anything yet

**Comment by negarbarooti** [comment]
I sent it to this email is it correct?

***@***.***

**Comment by negarbarooti** [comment]
[RTSTRUCT file](https://drive.google.com/file/d/1y5mBzTMkENNzHfe80xYaRcHuH19G88f5/view?usp=drivesdk) 
This is my RTSTRUCT file i sent it to the email but if you cant received it you can download it from above link

**Comment by bettar** [comment]
Fixed with release version 8.20.94

**Comment by negarbarooti** [comment]
alex thank you very much everything looks excellent

‫‪Alex Bettarini‬‏ ***@***.***‬‏> در تاریخ چهارشنبه ۲۰ ژوئیه
۲۰۲۲ ساعت ۱۲:۳۸ نوشت:‬
