### ISSUE TITLE
Looking for Beta tester volunteer for next release

### ISSUE THREAD

**Issue by bettar** [bettar/miele-lxiv#78]
I am preparing the next release as a Universal Binary app, so that it can run natively on both Intel and Apple Silicon machines (M1 and M2 processors). Because I don't own such a PC, I am asking if there is somebody with an `arm64` CPU if they can test a beta version of the app and report any problems. All you have to do is first install the app "TestFlight" from the Apple AppStore and let me know that you are available by contacting me at the email address shown in Miele-LXIV Help menu.

**Comment by sscotti** [comment]
I've got a MBP with an M1 Pro Chip.  Particularly interested in Windows/Linux ports also.
