### ISSUE TITLE
FONTS AND ANNOTATION TEXT SIZE

### ISSUE THREAD

**Issue by matar84** [bettar/miele-lxiv#79]
When I zoom the fonts, it doesn't work.

**Comment by bettar** [comment]
Please explain what you mean by "zoom the fonts"
Please explain what you mean by "it doesn't work"
What is your macOS version and CPU architecture ?
What are the steps to reproduce the issue ?
Attach any screenshot to illustrate the point, if necessary

**Comment by matar84** [comment]
zoom the fonts: increase the size of text annotation ( name, surname, study description etc.)
it doesn't work: It doesn't increase the size of text annotation.
macos version: 12.6
CPU architecture: M1 
steps to reproduce the issue: format - character - more big

**Comment by bettar** [comment]
Resolved with release 8.24.110. Now the functionality is:
`^+` or `^-` to adjust the ROI text annotations size
`⌘+` or `⌘-` to adjust the text annotations size (font name and colour can also be changed)
