### ISSUE TITLE
2D orthogonal MPR

### ISSUE THREAD

**Issue by ste142** [bettar/miele-lxiv#82]
I use a MacBook Pro 2016 with OS 12.6.1. Whenever I try to display images using 2D orthogonal MPR the app freezes and nothing works. I click 2D viewer and then select 2D orthogonal MPR. Displaying images using 3D MPR works.   I have tried to do 2D orthogonal MPR using Horos and it works fine.  Any idea on how to fix this issue?

**Comment by bettar** [comment]
Is your CPU Intel or AppleSilicon ?
Is your display Retina ?

**Comment by ste142** [comment]
MacOS 12.6.1
2.7 GHz Quad-Core Intel Core i7
15.4 inch Retina (2880x1880)
16GB RAM

**Comment by bettar** [comment]
Fixed for next release, expected early Apr 2023.
