### ISSUE TITLE
Problem 3D image shifting

### ISSUE THREAD

**Issue by techmdmac** [bettar/miele-lxiv#84]
Version 9.26 runnning in iMac Retina with mac OS Ventura 13.3.1. The image shifting problem persists when performing a fine cut on a 3D image (3D MIP or 3D Volume Rendering) and you want to pivot on it: the image shifts annoyingly towards the edges of the screen. Also when you want to export a 3D image (cmd+E) it comes out cropped. This behavior is similar to what happens in Horos RC5 and apparently is due to the lack of adjustment of the program to Retina displays. It doesn't happen when a lower resolution external monitor is connected to the Mac. Thank you.

**Comment by bettar** [comment]
Can you please explain in detail the steps after opening the 3D Volume Rendering, possibly attaching screenshots ?

**Comment by techmdmac** [comment]
Can you send me an email adress to send you a short videoclip via We Transfer ?
Thankyou !

**Comment by bettar** [comment]
You could use the email address shown in the app Help menu.

**Comment by bettar** [comment]
Fixed. The fix will be included in the next release expected end Apr 2023.
