### ISSUE TITLE
inappropriate Zoom when opening a image in 3D MPR

### ISSUE THREAD

**Issue by techmdmac** [bettar/miele-lxiv#87]
When a series is opened in 3D MPR the images appear with an inappropriate degree of Zoom. They should open to actual size, as they do in Horos 4RC5.

**Comment by bettar** [comment]
I tried to reproduce the issue you describe but it seems to be working okay for me with:

- Monterey 12.6.5, Intel, non-retina
- Ventura 13.3.1, Apple silicon, retina

What's your configuration ? Can you attach a screenshot please ?

**Comment by MEDISIS-PT** [comment]
I have the same problem
Mac M1 Pro Max Ventura 13.1
<img width="2010" alt="Screenshot 2023-05-29 at 09 01 55" src="https://github.com/bettar/miele-lxiv/assets/120523474/eab0242a-6181-4319-89a9-491da132830d">

**Comment by bettar** [comment]
See issue #93
