### ISSUE TITLE
Problem linking a study 

### ISSUE THREAD

**Issue by techmdmac** [bettar/miele-lxiv#89]
Version 9.26. Persist the problem linking a file (not copying, -only importing as link-) . The first time a file is linked and opened, everything works fine. If you close the application (Miele LXIV) and open that file again, the link has been lost, but the original file is at the same location . If you look at the main screen, the preview (bottom right) shows a blank image. The only solution I've seen is to relink, but it's really not very practical.

**Comment by bettar** [comment]
Is this related to issue #81  ?

**Comment by techmdmac** [comment]
It is most likely the same. Excuse the redundancy. All the best.
