### ISSUE TITLE
Blank Series Icon in Toolbar

### ISSUE THREAD

**Issue by ky-tech-guy** [bettar/miele-lxiv#9]
In the 2d viewer, the series icon on the toolbar does not show the series that has been selected. It appears blank. See the image below for details. I have noticed that if you right click on the image, the series icon will show the correct image. You can obtain the dataset.....at http://199.19.86.163:3333/main. Search for alveolar proteinosis. 
![836ec18e-d543-11e4-8f7c-0b45814cc205](https://cloud.githubusercontent.com/assets/10901615/6953745/60b4011e-d899-11e4-9e82-f9c4475f26f7.jpg)

**Comment by bettar** [comment]
The problem has been fixed for version "b10" to be released in the next few days.
