### ISSUE TITLE
Patient Name 

### ISSUE THREAD

**Issue by techmdmac** [bettar/miele-lxiv#91]
When a pacs query is performed, the lastname and firstname appear together, with no space between them. Version 9.26. macOS Ventura 13.3.1

**Comment by bettar** [comment]
Can you please attach a screenshot here, and send me the DICOM file privately for me to investigate the issue ?

**Comment by techmdmac** [comment]
I can’t show the name of a patient (by law is a private issue).The result of a query for “bettarini” shows: “bettarinialex”, without spaces.El 2 may 2023, a las 8:40, Alex Bettarini ***@***.***> escribió:﻿
Can you please attach a screenshot here, and send me the DICOM file privately for me to investigate the issue ?

**Comment by bettar** [comment]
Does it happen with any file or just one file ?
Are you talking about the Query window or the main database window ?

**Comment by techmdmac** [comment]
Does it happen with any file or just one file ?Any fileAre you talking about the Query window or the main database window ?Yes , query icon of de main database layout.El 2 may 2023, a las 10:40, Alex Bettarini ***@***.***> escribió:﻿
Does it happen with any file or just one file ?
Are you talking about the Query window or the main database window ?

**Comment by bettar** [comment]
The "Patient Name" column in the Query window does what you describe as an issue by design:

https://github.com/bettar/miele-lxiv/blob/fd330fe0cb4991e4c87910bee2ac59764ebbeb53/OsiriXClasses/DICOMFiles/dicomFile.mm#L230

**Comment by bettar** [comment]
I decided to go ahead and modify it as per your wish. The change will be included in the next release.

**Comment by techmdmac** [comment]
Thank you!El 2 may 2023, a las 14:12, Alex Bettarini ***@***.***> escribió:﻿
I decided to go ahead and modify it as per your wish. The change will be included in the next release.
