### ISSUE TITLE
curved MPR doesn't work fine

### ISSUE THREAD

**Issue by techmdmac** [bettar/miele-lxiv#93]
It is virtually impossible to perform a curved MPR with the zoom level constantly changing between different views when attempting to traverse the artery. Zoom, instead of growing the image, only enlarges a small center box. Even some of the views disappear. I used macOS Ventura 13.3.1 MBP Intel.
<img width="1773" alt="Scree capture" src="https://github.com/bettar/miele-lxiv/assets/58887624/ec37c8af-6f8e-4861-94d9-4c42b11eabbf">

**Comment by bettar** [comment]
Fixed in version 9.34 expected to be released beginning of Oct 2023

**Comment by techmdmac** [comment]
Good good news !! Thank you for your job.El 26 sept 2023, a las 17:57, Alex Bettarini ***@***.***> escribió:﻿
Fixed in version 9.34 expected to be released beginning of Oct 2023
