### ISSUE TITLE
unable to open studies

### ISSUE THREAD

**Issue by snehaht86** [bettar/miele-lxiv#94]
was working fine a month ago . now it does not open any study.

**Comment by bettar** [comment]
Can you please spend a few more words to explain your problem ? What changed since one month ago, did you upgrade macOS version ? did you upgrade the app version ? What's your current version of everything ? Are you able to verify if it happens on other machines too ?

**Comment by bettar** [comment]
I am closing the issue because you didn't provide enough information in your original post, and you don't seem to be interested in providing any answers.
