### ISSUE TITLE
Automatic and unwanted printing of Siemens CT files

### ISSUE THREAD

**Issue by techmdmac** [bettar/miele-lxiv#95]
During the import of anonymized CT studies from Siemens, non-image files referring to radiation dose (Dose Report) are automatically sent to the print queue. This happens regardless of the printer model available (HP, Canon,...). This does not happen in Horos.
<img width="1437" alt="Miele Screen Capture" src="https://github.com/bettar/miele-lxiv/assets/58887624/17d1f99b-38f6-4b93-9a5c-b4da0eee7996">

**Comment by bettar** [comment]
It is a small bug in the code that creates a PDF file (using the printer API). It's been fixed for the next release 9.31.122 expected middle of July 2023. This comment covers the yellow arrow in your screenshot. I am not sure what is going on about the red arrow.

**Comment by ruiclaro1** [comment]
I am dealing with the same problem randomly when I import an exame.
How can I fix it?
Here an example for today (it prints a lot of files...)
![IMG_9032](https://github.com/bettar/miele-lxiv/assets/138897928/b49c3a3e-6131-4048-b1cd-1b25ae7baf7b)

**Comment by bettar** [comment]
> I am dealing with the same problem randomly when I import an exame.
> How can I fix it?

As announced in the message above yours, you just have to wait a few days for the new release. Or you can just create a dummy printer, set it as defaults and the print out will go there, details here [How to Setup a Null Printer on macOS](https://www.papercut.com/kb/Main/SetupNullPrinterOnMac)
