### ISSUE TITLE
3D MPR thick Slab Average modality (version 9.31.122) on macOS Ventura 13.5

### ISSUE THREAD

**Issue by techmdmac** [bettar/miele-lxiv#96]
When you perform a Thick Slab visualization in "Average" mode, the image obtained is that of the "minIP" modality and not that of "Average".  In Horos it is correctly represented (see attached files).

![Horos 3D MPR](https://github.com/bettar/miele-lxiv/assets/58887624/3fe2c720-8d39-4522-9e35-4bc3b6e72079)
<img width="2559" alt="Miele LXIV 3D MPR" src="https://github.com/bettar/miele-lxiv/assets/58887624/d51b24f0-db2b-4b47-a9dc-6ea2cb72d5d6">

**Comment by bettar** [comment]
Fixed with release 9.32

**Comment by techmdmac** [comment]
Hello Mr. Bettarini

Thank you very much for your work and your kindness for trying to solve each problem. Let me use your kindness a bit to ask if you find it difficult to solve the curved MPR problem (issue #93). It's really the only relevant problem I see left with the Miele LXIV, which has been greatly improved of late. A cordial greeting.
