### ISSUE TITLE
TIFF import

### ISSUE THREAD

**Issue by oseynnes** [bettar/miele-lxiv#97]
Despite unchecking the option `Import DICOM file format only (ignore JPEG, TIFF, LSM, Analyse...)` in `Settings` > `Database`, the import of TIFF files does not work. The import process seems to work fine but the image does not appear in the list of imported files.

**Comment by bettar** [comment]
To me it doesn't make sense that you are trying to import a TIFF file into a DICOM viewer: where should the DICOM tags come from ?

**Comment by oseynnes** [comment]
Importing TIFF files is useful for teaching. We need to process the DICOM files before they can be used for teaching but this results in their conversion to TIFF. The advantage of this format though, is that unlike JPEG they can contain metadata. In the case of converted DICOM files, they retain the tags in the metadata.

**Comment by bettar** [comment]
Can you please send me an example of such TIFF file so I can check how it's handled by the app ?

**Comment by oseynnes** [comment]
Sure. Thanks! See the attached example.


[2040.tiff]
On 6 Sep 2023, at 15:39, Alex Bettarini ***@***.***> wrote:



Can you please send me an example of such TIFF file so I can check how it's handled by the app ?

**Comment by bettar** [comment]
Unfortunately the announced file 2040.tiff was not attached to the email I received.

**Comment by bettar** [comment]
> We need to process the DICOM files before they can be used for teaching but this results in their conversion to TIFF. 

I don't understand why you first convert DICOM to TIFF, and then you want to import back TIFF as DICOM. Please explain.

**Comment by oseynnes** [comment]
Here is a link to the file<https://nihno-my.sharepoint.com/:i:/g/personal/oliviers_nih_no/EcaBsSlbPT5NjetuR9GU_vkBaCMkME7i5LygXaPUCNSCpQ?e=Zd5zj6> (not sure what happened to the attachment).

The reason why we need to convert to TIFF is because one of the steps is anonymisation. With our ultrasound machine, the patient name is written on the image (therefore anonymising the tags is not sufficient). Since we have many images, it would take too long to select this name and change the pixel colour within Miele-lxiv, for each image. We do this programmatically with another programme (ImageJ) but don’t know how to save it again as DICOM, we get a TIFF file.


On 6 Sep 2023, at 17:32, Alex Bettarini ***@***.***> wrote:



We need to process the DICOM files before they can be used for teaching but this results in their conversion to TIFF.

I don't understand why you first convert DICOM to TIFF, and then you want to import back TIFF as DICOM. Please explain.

**Comment by bettar** [comment]
I made a small change (for next release of the app) that allows importing tif (and other) images. Are you happy with just viewing the image or do you also need to recover the DICOM information from the tif file metadata ?

**Comment by oseynnes** [comment]
Thank you very much! I think that in Osirix, only the images are imported, but if you have the possibility to retrieve the DICOM tags included in the TIFF header it would be perfect for our purpose.


On 7 Sep 2023, at 08:43, Alex Bettarini ***@***.***> wrote:



I made a small change (for next release of the app) that allows importing tif (and other) images. Are you happy with just viewing the image or do you also need to recover the DICOM information from the tif file metadata ?

**Comment by bettar** [comment]
Just as an aside comment, you said that a problem with the anonymization is that "the patient name is written on the image" therefore you need to use ImageJ. You could do all that in Miele-LXIV by defining a rectangular ROI that covers the patient name, (name it something other than "Undefined"), select "Propagate Selected ROI...", then select "Set Pixel values to...". Finally export it as DICOM, and anonymize the series that you have exported.

**Comment by oseynnes** [comment]
Yes, you are right. The issue with this solution was that we needed to de-anonymise the images as part of the assessment. We could have done it by attributing a specific tag to the images but it was faster to do it programmatically. I understand why the software works in this way for clinical purposes but for research/teaching, we need to keep track of the anonymisation to revert it and at the moment, I don’t think that the anonymisation of the DICOM files comes with information for de-anonymisation.


On 7 Sep 2023, at 10:00, Alex Bettarini ***@***.***> wrote:



Just as an aside comment, you said that a problem with the anonymization is that "the patient name is written on the image" therefore you need to use ImageJ. You could do all that in Miele-LXIV by defining a rectangular ROI that covers the patient name, (name it something other than "Undefined"), select "Propagate Selected ROI...", then select "Set Pixel values to...".

**Comment by bettar** [comment]
The problem with recovering the DICOM tags from the imported TIF is that from what I saw the formatting and encoding of those tags is specific to ImageJ so the best approach would be to create a plugin that does just that.
Alternatively, create a separate CLI utility that converts those TIF files created by ImageJ back to DICOM.

**Comment by oseynnes** [comment]
Sure! I didn’t expect it since it was not in the original code, I just thought I’d raise the case because the import of TIFF images seemed implemented. Thank you again for considering it and for adding it to the next update.

On 7 Sep 2023, at 10:30, Alex Bettarini ***@***.***> wrote:



The problem with recovering the DICOM tags from the imported TIF is that from what I saw the formatting and encoding of those tags is specific to ImageJ so the best approach would be to create a plugin that does just that.

**Comment by bettar** [comment]
Fixed with version 9.33
